
development:
  adapter: postgresql
  encoding: unicode
  database: nephro_pal_development
  username: lukewalker
  password:
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  encoding: unicode
  database: nephro_pal_test
  username: lukewalker
  password:
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  encoding: unicode
  database: nephro_pal_production
  username: lukewalker
  password:
  pool: 5
  timeout: 5000
